[tool.ruff]
lint.select = ["ALL"]
lint.extend-ignore = [
    "D211",     # One blank line before class
    "D212",     # Multiline summary on second line
    "EM101",    # Don't agree with readability concern
    "S311",     # Allow pseudo-random numbers
]

[tool.ruff.lint.per-file-ignores]
"squib/*" = [
    "FA102",    # Python 3.10 does not require from __future__ statement
    "G004",     # Allow f-strings in log statements
    "TCH002",   # Python 3.10 compiles as type-checking
]
"squib/evaluation/parse_results.py" = [
    "T201",     # Allow print to stdout
]
"tests/*" = [
    "INP001",   # Do not use an __init__.py for unit test directory
    "D100",     # Do not use module docstring in unit test files
    "D103",     # Do not require method docstrings
    "S101",     # Asserts needed for unit tests
    "SLF001",   # Allow access to private methods for testing
    "TCH002",   # Python 3.10 compiles as type-checking
]
"notebooks/experiments.py" = [
    "INP001",   # Do not install notebooks directory
    "TCH002",   # Python 3.10 compiles as type-checking
]